### ISSUE TITLE
Is it possible to import and use sudachipy's full dictionary directly?

### ISSUE THREAD

**Issue by BLKSerene** [WorksApplications/SudachiPy#100]
Since I need to package and distribute my program which includes SudachiPy to my users, the symlink would not be very reliable if I want to use the full version of SudachiPy's dictionary. So is there any way to import and use sudachipy's dictionary directly instead of run the linking command before that (the linking command would fail if the user do not have admin privileges), just like spaCy:

```
import spacy
nlp = spacy.load("en_core_web_sm")
```

**Comment by izziiyt** [comment]
Now it's impossible to relate self-downladed dictionary to program. 

We haven't considered this problem.  This should be solved.
> the linking command would fail if the user do not have admin privileges

Could you tell me why it's not very reliable for using `full version of SudachiPy's dictionary` ?
> the symlink would not be very reliable if I want to use the full version of SudachiPy's dictionary

**Comment by BLKSerene** [comment]
I'm trying to use `SudachiPy` in my project which will be packaged into an executable program using `PyInstaller` and then distributed to my users. The symlink works with no problem on my own computer which I use to develop my program, but when the program and all dependencies are frozen into executables, the symlink might stop working. (Though I haven't tested it yet.)
