### ISSUE TITLE
Release v0.4.3

### ISSUE THREAD

**Issue by hiroshi-matsuda-rit** [WorksApplications/SudachiPy#115]
@sorami Could you please release recent develop branch as `v0.4.3` and deploy it to `pypi.org`?

**Comment by sorami** [comment]
Got it, let me handle that later today.

**Comment by sorami** [comment]
Done :tada: 

- [Release v0.4.3 · WorksApplications/SudachiPy](https://github.com/WorksApplications/SudachiPy/releases/tag/v0.4.3)
- [SudachiPy · PyPI](https://pypi.org/project/SudachiPy/0.4.3/)

**Comment by hiroshi-matsuda-rit** [comment]
Thank you so much! @sorami
