### ISSUE TITLE
Strange behavior when indexing into MorphemeList

### ISSUE THREAD

**Issue by polm** [WorksApplications/SudachiPy#136]
Sample code:

    from sudachipy import dictionary
    tok = dictionary.Dictionary().create()
    sent = tok.tokenize("コトノハ")
    # this does not cause an error
    word = sent[1000]
    # this causes an error because the word does not exist
    word.surface()

This wouldn't come up in normal usage but it seems really weird. I guess in `__getitem__` there should be a check against the length of `path`?

**Comment by sorami** [comment]
@polm Thanks!

According to @kazuma-t , for the Java version he intentionally did not check the index range to make it slightly faster.

For the Python version I believe we should check the range (it is pretty slow already anyway ... haha). Fix and test in #137
