### ISSUE TITLE
sudachipy/tokenizer.pyx: /dev/null is left opened.

### ISSUE THREAD

**Issue by sukeya** [WorksApplications/SudachiPy#167]
Hi,
The following member variable of class Tokenizer seems not to be closed.
I think it should be closed in destructing or deleted (because it isn't used in this library).

https://github.com/WorksApplications/SudachiPy/blob/03d9ff8e7094859275984ee718e08c3fcefaeb6b/sudachipy/tokenizer.pyx#L112

**Comment by eiennohito** [comment]
0.6.0 does not has this problem as it does not leak file descriptors.
We will not fix this issue in 0.5.* branch though.
