### ISSUE TITLE
Consider archiving this repo

### ISSUE THREAD

**Issue by polm** [WorksApplications/SudachiPy#169]
Since development has moved to the Rust version, if this version is not going to be maintained (which seems likely) it might be best to archive it to make it clear it's not active. The note in the README is helpful but not as clear as the banner that archived repos show.

**Comment by eiennohito** [comment]
@kazuma-t what do you think?

I'd say let's wait 6 months from the SudachiPy 0.6.0 release and if nothing really serious comes up, let's archive this repo.

**Comment by kazuma-t** [comment]
@eiennohito I agree with you.

**Comment by polm** [comment]
Just going to bump this, since it's been a year and there haven't been any significant changes.

**Comment by eiennohito** [comment]
@kazuma-t

**Comment by kazuma-t** [comment]
I'll archive it now.
