### ISSUE TITLE
How to pack sudachi with pyinstaller?

### ISSUE THREAD

**Issue by CberYellowstone** [WorksApplications/SudachiPy#173]
すみません。日本語が苦手なので英語を使います( _←機械翻訳、敬語を使っていないかもしれませんが、申し訳ありません_ )
I want to pack my code which has used SudachiPy with **pyinstaller**,
however, when I pack it with this command: 
`pyinstaller.exe -D .\main.py --collect-data sudachidict_full --hidden-import sudachidict_full`
the packed exe file can't run and it reported this:
```
Traceback (most recent call last):
  File "GUI.py", line 15, in <module>
    from Segmentation import splitWords
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "Segmentation.py", line 23, in <module>
    _sudachi = dictionary.Dictionary(dict="full").create()
Exception: Error loading config: IO Error: The system cannot find the path specified. (os error 3)
[464736] Failed to execute script 'GUI' due to unhandled exception!
```
More infomation:
`Python 3.7.9`  `pyinstaller 4.9` ` sudachiipy 0.6.2` system: `windows 10`

so what should I do to pack my code?
P.S. I had been found there was a success example to pack sudachi with pyinstaller, the link follow↓
here's [The Success Example](https://linuxtut.com/en/b4e45c43cb565f3a970a/), but it did't tell us how it made it
よろしくお願いしまーす

**Comment by eiennohito** [comment]
I am not sure about the resulting format of the pyinstaller, but the possible problem could be related to the fact that we sort of abuse the installation script of sudachidict packages to download a precompiled dictionary from the internet.
We also assume the standard Python site-packages layout for libraries when searching for the precompiled dictionary. You can pass the absolute path to the downloaded dictionary `dictionary.Dictionary(dict="</absolute/path/to/dictionary/here>")`, (0.6.0+ feature) if pyinstaller does something fancy to the site-packages layout. I am not familiar with it to give further advice.

**Comment by CberYellowstone** [comment]
Solution:
```
    sudachi_config_path = path.abspath(path.join(path.dirname(__file__), r'sudachipy\resources\sudachi.json'))
    _sudachi = dictionary.Dictionary(dict='full',config_path=sudachi_config_path).create()
```
It seems that it was not the dict's import problem, but the config's(笑)

**Comment by acro5piano** [comment]
Thanks @CberYellowstone , I've fixed the issue referring to your solution.

```py
import os
import sys

from sudachipy import Dictionary, Tokenizer


def is_production_bundle() -> bool:
    """Determine if application is a script file or ditribution bundle for Windows.
    See also: https://stackoverflow.com/a/42615559/4287971
    """
    return getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")


def get_bundle_dir_or_chdir() -> str:
    """Returns path to the distribution bundle directory.
    e.g.)
      - C:\\Users\\Kazuya\\Document\\myapp\\out\\runtime\\main (on bundled windows environment)
      - /home/kazuya/myapp     (on linux environment)
    """

    if is_production_bundle():
        return os.path.dirname(sys._MEIPASS) + "\\main"  # type:ignore
    else:
        return os.getcwd()


def create_tokenizer() -> Tokenizer:
    """Create sudachipy tokenizer.
    The directory strucuture of distributed app is assumed to be:
    myapp/out/runtime/main
        |-- main.exe
        |-- mylib.py
        |-- sudachipy
        |   `-- resources
        |      `-- sudachi.json
        `-- sudachidict_core
            `-- resources
               `-- system.dic
    """
    sudachi_config_path = path.abspath(path.join(get_bundle_dir_or_chdir(), r"sudachipy\\resources\\sudachi.json"))
    sudachi_dict_path = path.abspath(path.join(get_bundle_dir_or_chdir(), r"sudachidict_core\\resources\\system.dic"))
    dict = Dictionary(dict_type="core", config_path=sudachi_config_path, dict=sudachi_dict_path)
    return dict.create()
```

During debugging, I saw this error message which isn't impressive. Actually it means `config_path` or `dict` not found.

```
ValueError: "dict_type" must be "small", "core", or "full".
```

**Comment by eiennohito** [comment]
Do not use `dict` and `dict_type` arguments together. Even more, `dict_type` is a deprecated argument do not use it at all. Using only `dict` should suffice (with 0.6.0+)

**Comment by CberYellowstone** [comment]
> Thanks @CberYellowstone , I've fixed the issue referring to your solution.
> 
> ```python
> import os
> import sys
> 
> from sudachipy import Dictionary, Tokenizer
> 
> 
> def is_production_bundle() -> bool:
>     """Determine if application is a script file or ditribution bundle for Windows.
>     See also: https://stackoverflow.com/a/42615559/4287971
>     """
>     return getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")
> 
> 
> def get_bundle_dir_or_chdir() -> str:
>     """Returns path to the distribution bundle directory.
>     e.g.)
>       - C:\\Users\\Kazuya\\Document\\myapp\\out\\runtime\\main (on bundled windows environment)
>       - /home/kazuya/myapp     (on linux environment)
>     """
> 
>     if is_production_bundle():
>         return os.path.dirname(sys._MEIPASS) + "\\main"  # type:ignore
>     else:
>         return os.getcwd()
> 
> 
> def create_tokenizer() -> Tokenizer:
>     """Create sudachipy tokenizer.
>     The directory strucuture of distributed app is assumed to be:
>     myapp/out/runtime/main
>         |-- main.exe
>         |-- mylib.py
>         |-- sudachipy
>         |   `-- resources
>         |      `-- sudachi.json
>         `-- sudachidict_core
>             `-- resources
>                `-- system.dic
>     """
>     sudachi_config_path = path.abspath(path.join(get_bundle_dir_or_chdir(), r"sudachipy\\resources\\sudachi.json"))
>     sudachi_dict_path = path.abspath(path.join(get_bundle_dir_or_chdir(), r"sudachidict_core\\resources\\system.dic"))
>     dict = Dictionary(dict_type="core", config_path=sudachi_config_path, dict=sudachi_dict_path)
>     return dict.create()
> ```
> 
> During debugging, I saw this error message which isn't impressive. Actually it means `config_path` or `dict` not found.
> 
> ```
> ValueError: "dict_type" must be "small", "core", or "full".
> ```

you can look for one of my repository  which including a available example if you are still confused
this is the pyinstaller .spec file: [TransAssistant_core-lite.spec](https://github.com/GayWindTech/TransAssistant/blob/main/TransAssistant_core-lite.spec)
and this is my code: [Segmentation.py](https://github.com/GayWindTech/TransAssistant/blob/main/Segmentation.py)

**Comment by acro5piano** [comment]
@eiennohito 

> Do not use `dict` and `dict_type` arguments together. Even more, `dict_type` is a deprecated argument do not use it at all. Using only `dict` should suffice (with 0.6.0+)

Thank you for the information!

**Comment by acro5piano** [comment]
@CberYellowstone 

Thanks! I've implemented it by manually copying a dictionary after build, but defining them in .spec file should be the more elegant and robust way.
