### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by marzenakrp** [WorksApplications/SudachiPy#21]
Hi, I actually have some problems with installation.
I cannot install it with pip because I'm getting the following error:

` with open("README.md", encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
`

When I try to use pip3 it works but then I can't import it to python (no module error)

**Comment by izziiyt** [comment]
@MaraPL 

Probably it's too late for you but I'll answer your question.

> I cannot install it with pip because I'm getting the following error:

This message looks that you are using python2.
Have you checked your python version ? README says Sudachi supports version over 3.5

> When I try to use pip3 it works but then I can't import it to python (no module error)

Have you installed sudachi package in your proper environment ?
Have you confirmed sudachi package installed in proper dist-pakcages directory ?
