### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by toshifumikuroda** [WorksApplications/SudachiPy#22]
I got following error when splitting mobile app store description.
The description is 
'Take advantage at the  Black Friday sale  with  50% off.Now for $1.99 for this successful Keyboard Application at  Google Play, Save money and tell your friends. The sale is extended till Monday , November 30, 2015. Don’t miss it! ai.type のスマートフォンやタブレットのための賢い、最もパーソナライズされたのキーボードです。全世界で2500万人を超えるユーザーにより、我々は、メッセージングの経験を変換する。\xa0私たちのアプリは、あなたが好きなようにあなたの文章のスタイルを学習することにより、それがカスタマイズにあなたを可能にし、パーソナライズのキーボードより良く、より速く入力できます。***すべての私達のプレミアム機能（予測、補完、訂正、スワイプ、絵文字など）を楽しみ、すべての回でそれらを使用し続けています。オリジナル★機能セットのハイライト★デザインキーボードレイアウトの変更、テーマ、色、フォント、800以上の絵文字を使用し、正確にあなたがしたいように自分を表現。★新機能★♦自由なテーマの何千人もの - 私たちのテーマ市場の一環として、何千もの中から自由で魅力的なキーボードのテーマのいずれかの利用可能なテーマを選択してください。♦デザインと独自のテーマを共有する：\to デザインのパーソナライズされたレイアウト（背景、色、およびフォント）、\to💫共有のテーマや他の何百万ものユーザーが、参照レートと⬇それらをダウンロードすることができます我々のアプリのテーマ市場へのテーマをアップロードします。♦自動絵文字🙏🚄💑を提案し、スクロール可能な😄レイアウト\to 私たちが助けて、あなたが使う言葉とコンテキスト😍🍩に基づいて右の絵文字を提案してみましょう。\to あなたは簡単に完全な絵文字パック（> 800）をナビゲートするのを助ける私たちの新しい絵文字スクロール可能なレイアウトをお楽しみください。♦の改良補正予測。★オリジナル★\t♦次単語予測、完成＆自動補正 - コンテキストベースの次の単語予測し、独自のユニークな文体に基づいて、（英語で文法チェックを含む）を自動補正。\t♦スワイプ - キーのキーから指をスワイプすることによってより速く書く。\t♦パーソナライズの🔧キーボードのルックアンドフィール、機能性と、独自のカスタムキー＆ショートカットを作成。\t\to 動的に必要に応じて、キーボードのサイズのサイズを変更します。\t\to あなたの背景画像として任意の画像を設定します。\t\to 主要キーボード画面の中から、効率的に数字、句読点（およびその他）の文字を追加するために私たちのトップ（5日）の行を使用してください。\t\to ロング任意のキーを押して、便利に、アクセントや代替文字を使用します。\t♦語キーボード検索の🔎あなたはすぐにテキストを見つけること。\t♦音声ナレーションには - あなたがそれらを入力するよう🔊言葉を指示する。\t♦新規ロリポップ材料設計＆新素材のキーボード。\t♦言語サポート - 自動予測、40以上の言語で完了し、訂正能力。\t♦プライバシー - あなたのプライバシーは私達の主な関心事である。私たちは、あなたのデータを共有しないか、パスワードフィールドから学ぶん。テキストは暗号化され、プライベートのまま。★パーミッションので 説明★連絡先データベースを読む権限を連絡先リストに基づいて名前を生成するために必要とされる。SMSを読み取る権限がSMSの内容に基づいてワードを生成するために必要とされる。すべての情報は、局部的にスマートフォンの語彙に保存されます。★サポート＆質問★動画、回答＆ヒントを見つけるために私たちのヘルプ＆よくある\u200b\u200b質問のページを訪問し、サポート要求を開きます。http://www.aitype.com/support/またsupport@aitype.comに私達に電子メールを送ったり、Facebook上で私たちを訪問することができます：http://www.facebook.com/pages/aitype。'

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-34-7abae29033da> in <module>
      1 for text in jp_descriptions.dropna():
----> 2     sudachi_split_words(text)

<ipython-input-3-68a1a24d981d> in sudachi_split_words(text)
      4     wakati_words = []
      5     for token in tokens:
----> 6         hinshi = token.part_of_speech()[0]
      7         wakati_words.append(token.normalized_form())
      8     return wakati_words

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/morpheme.py in part_of_speech(self)
     15 
     16     def part_of_speech(self):
---> 17         wi = self.get_word_info()
     18         return self.list.grammar.get_part_of_speech_string(wi.pos_id)
     19 

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/morpheme.py in get_word_info(self)
     45     def get_word_info(self):
     46         if not self.word_info:
---> 47             self.word_info = self.list.get_word_info(self.index)
     48         return self.word_info

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/morphemelist.py in get_word_info(self, index)
     34 
     35     def get_word_info(self, index):
---> 36         return self.path[index].get_word_info()
     37 
     38     def split(self, mode, index, wi):

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/latticenode.py in get_word_info(self)
     44     def get_word_info(self):
     45         if self.word_id >= 0:
---> 46             return self.lexicon.get_word_info(self.word_id)
     47         elif(self.extra_word_info is not None):
     48             return self.extra_word_info

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/dictionarylib/lexiconset.py in get_word_info(self, word_id)
     39 
     40     def get_word_info(self, word_id):
---> 41         return self.lexicons[self.get_dictionary_id(word_id)].get_word_info(self.get_word_id(word_id))
     42 
     43     def get_dictionary_id(self, word_id):

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/dictionarylib/doublearraylexicon.py in get_word_info(self, word_id)
     49 
     50     def get_word_info(self, word_id):
---> 51         return self.word_infos.get_word_info(word_id)

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/dictionarylib/wordinfolist.py in get_word_info(self, word_id)
     17         pos_id = int.from_bytes(self.bytes[index:index+2], 'little')
     18         index += 2
---> 19         normalized_form = self.buffer_to_string(index)
     20         index += 1 + 2 * len(normalized_form)
     21         if not normalized_form:

~/Dropbox/MobileApp/main/src/sudachipy/sudachipy/dictionarylib/wordinfolist.py in buffer_to_string(self, offset)
     48         offset += 1
     49         end = offset + 2 * length
---> 50         return self.bytes[offset:end].decode("utf-16-le")
     51 
     52     def buffer_to_int_array(self, offset):

~/anaconda3/envs/mobileapp/lib/python3.7/encodings/utf_16_le.py in decode(input, errors)
     14 
     15 def decode(input, errors='strict'):
---> 16     return codecs.utf_16_le_decode(input, errors, True)
     17 
     18 class IncrementalEncoder(codecs.IncrementalEncoder):

UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 40-41: illegal UTF-16 surrogate

**Comment by izziiyt** [comment]
I assumed this is caused by emoji. (I met same error when the text contains emoji.)

So, I think easiest solution is emoji removal beforehand like

```
# copied from http://yukinoi.hatenablog.com/entry/2018/05/29/120000
import emoji

words = list(filter(lambda x: x in emoji.UNICODE_EMOJI, words))
```

However, I think we, developer team, has 2 options for this topic

1. Sudachi supports emoji removal as plugin
2. Sudachi requires users emoji removal

**Comment by toshifumikuroda** [comment]
Thank you for your suggestion.
I think emoji has its meanings. When analysing textdata by distributed
semantics like word2vec, removing "🐈", but not removing '猫' seems arbitrary.

I hope that sudachi adds emoji into its dictionary to split emoji as one word.
Thank you,
Toshi

**Comment by izziiyt** [comment]
> I hope that sudachi adds emoji into its dictionary to split emoji as one word.

Thanks good idea, but I can't promise we'll do it. Now meanings and grammatical feature of emoji should be defined by users for their purpose. However, if we find requirements like yours are increasing and emoji is good theme for next step of Sudachi, probably we'll do it. Thank you for your good FB.

p.s) The problem that SudachiPy can't be applied to emoji-contained text because of UnicodeDecodeError will be resolved soon. Sorry for your inconvenience.

**Comment by izziiyt** [comment]
I met this bug during adding test code. I reopened this issue and put in a milestone.

**Comment by izziiyt** [comment]
I probably fixed. Why I used "probably" is because I couldn't reproduce same error with same text.
If same error occurs, reopen or make new issue.
