### ISSUE TITLE
Dictionary file management structure

### ISSUE THREAD

**Issue by sorami** [WorksApplications/SudachiPy#4]
Currently, the dictionary file is not included in the repository. We would like to make a flow to get these resources via the code, like [NLTK](https://www.nltk.org/data.html) (e.g., `import nltk; nltk.download()`) or [spaCy](https://spacy.io/usage/models) (e.g., `$python -m spacy download en`).

**Comment by fhudi** [comment]
Dictionary is put on nexus dictionary https://oss.sonatype.org/content/repositories/snapshots/com/worksap/nlp/sudachi/

Will implement download and unpack programmatically function.

**Comment by izziiyt** [comment]
with #46, SudachiPy can manage dictionary file using `pip` and `sudachipy link` now.

However, dictionary file is too big to publish via PyPI so like
```
pip install sudachi-dic-full
```
is impossible.

```
pip install https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20190531.tar.gz
```

is the current solutoin.

@sorami 's idea
>Currently, the dictionary file is not included in the repository. We would like to make a flow to get these resources via the code, like NLTK (e.g., import nltk; nltk.download()) or spaCy (e.g., $python -m spacy download en).

is still active.

**Comment by fhudi** [comment]
I have tried this and it worked like magic! kudos

@sorami 's objective
>  We would like to make a flow to get these resources via the code

IMO, objective has been achieved.
For the management of published dictionary itself is out of this issue's scope.

If there is no problem we can close this issue.
tag: @kazuma-t

**Comment by izziiyt** [comment]
@lintaoren I agree with you, objective has been almost achieved.  
The current problem I mentioned https://github.com/WorksApplications/SudachiPy/issues/4#issuecomment-508972605
can be taken over to #47 .
