### ISSUE TITLE
Register module archive to PyPI

### ISSUE THREAD

**Issue by hiroshi-matsuda** [WorksApplications/SudachiPy#41]
There are big needs for using SudachiPy as a library hence I hope to do it by:
pip install SudachiPy

**Comment by hiroshi-matsuda** [comment]
PyPI does not allow to upload > 50MB archives. It seems to small to include the dictionary. But still there are strong needs to publish the archive without dictionary from PyPI.

**Comment by izziiyt** [comment]
This feature is related to #6 
I know we need complete #4 beforehand.
I'll do #4 and #6 as next step

**Comment by hiroshi-matsuda-rit** [comment]
Thanks, @izziiyt . Uchida-san requested me to order this task to you.
Anyway, I created a PR using latest SudachiPy in spaCy repository.
https://github.com/explosion/spaCy/pull/3899

**Comment by izziiyt** [comment]
@hiroshi-matsuda I merged 2 MR. And make 2 releases `v0.1.2` and `v0.2.0`. The latest SudachiPy is same as `v0.2.0`. Please make sure that `v0.2.0` linearly depends on `v0.1.2`.

**Comment by hiroshi-matsuda-rit** [comment]
@izziiyt Thanks a lot! I found setup.py correctly merged. I'd like to use 0.3.0 for spaCy and GiNZA new models.

**Comment by izziiyt** [comment]
From v0.2.1 Users can download archive without dictionary from PyPI so I'll close here.  
About management dictionary data, see #4.
