### ISSUE TITLE
keep dictionary URL up-to-date

### ISSUE THREAD

**Issue by izziiyt** [WorksApplications/SudachiPy#47]
in

- setup.py
- requirements.txt 
- README.md

exact dictionary URL written like
```
"SudachiDict_core @ https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20190531.tar.gz"
```

we need rewrite when dictionary updates. 

For easy operation, we need introduce approach like bellows

1. prepare proxy server to route exact URL
2. parse URL index file on web like nltk (https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml)

**Comment by izziiyt** [comment]
F.Y.I
https://github.com/WorksApplications/SudachiPy/issues/4#issuecomment-508972605

**Comment by sorami** [comment]
Up-to-date dictionaries now managed as Python packages. #119
