### ISSUE TITLE
Proposal to simplify mode setting

### ISSUE THREAD

**Issue by polm** [WorksApplications/SudachiPy#68]
In example code I noticed the mode is passed to `tokenize` on every call, like this:

```
# From the README
mode = tokenizer.Tokenizer.SplitMode.C
[m.surface() for m in tokenizer_obj.tokenize("医薬品安全管理責任者", mode)]
```

That strikes me as weird, since I assume usually you'll pick a single tokenization mode for any instance of a tokenizer and use it the whole time. Would it be possible to add a default mode when the tokenizer is constructed, something like this?

```
mode = tokenizer.Tokenizer.SplitMode.C
tokenizer_obj = dictionary.Dictionary().create(mode=mode) 
tokenizer_obj.tokenize("医薬品安全管理責任者") # uses mode C
```

If this is acceptable I can submit a PR.

**Comment by izziiyt** [comment]
@polm Thank you for your good suggestion.

In my personal opinion, your idea is reasonable as a user and setting default mode when initiating tokenizer is simple solution. ~~but I don't know how it is meaningful that `mode C` is assumed to be default in implementation .~~  ~~And, this is important point, this is incompatible change with Java Sudachi. I need to ask @kazuma-t about these two points.~~ (mode is already default specified variable in function tokenize)

@kazuma-t Do you think @polm 's opinion ? ~~and interface incompatibility ?~~

**Comment by izziiyt** [comment]
@polm Sorry for having you wait.  Your suggestion is acceptable.  Thanks.
