### ISSUE TITLE
faster parsing

### ISSUE THREAD

**Issue by izziiyt** [WorksApplications/SudachiPy#74]
guessed bottle necks are
- fetch word info from dictionary
- fetch connection weight from matrix

**Comment by izziiyt** [comment]
- [x] cythonize dartsclone (small effect to performance)
- [x] connection matrix access
- [x] parameterlist access
- [x] character type access
- [ ] text builder
- [ ] path rewrite plugin
- [ ] mecab oov plugin
- [ ] wordinfo access (memory usage vs speed)

**Comment by polm** [comment]
Hey, what's the status of this project? If I could help with Cythonizing SudachiPy I'd be glad to do so.

**Comment by izziiyt** [comment]
@polm I'm welcome your contribution 👍  I don't have enough time until Feb due to my own business work/private. So I think your contribution won't conflict with ours.

@sorami We should write contribution guidelines or coding guidelines to share our coding principal for PR including some amout of line changes like @polm may create. I want to discuss  with you directly, I'll reach you via slack !

**Comment by polm** [comment]
Thanks, good to know! Not sure I'll get started on this before the new year but I'll definitely have time in January.

**Comment by polm** [comment]
Hello, I ended up not having time for this in January - sorry it took so long, but I'm looking at it now.

**Comment by polm** [comment]
Worked on this some more today, it's in the `cython` branch in my fork. Based on my benchmark processing time went from roughly 50s to 12s. (This is faster than I reported in my latest PR because that was using cProfile, which slowed things down.)

**Comment by sorami** [comment]
@polm , thank you, that sounds awesome!!

I probably won't have time for today and tomorrow, but let me check and merge in the next few days.

**Comment by eiennohito** [comment]
0.6.0 is ~30x faster
