### ISSUE TITLE
handling alphabet

### ISSUE THREAD

**Issue by KHiyowa** [WorksApplications/SudachiPy#82]
SudachiPy's alphabet handling is defferent from Sudachi(Java).

example: ideco
Sudachi: 
ideco
ideco   名詞,普通名詞,一般,*,*,*        iDeCo
EOS

SudachiPy:
ideco
id      名詞,普通名詞,一般,*,*,*        ID
eco     名詞,普通名詞,サ変可能,*,*,*    エコ
EOS

Probably, it is caused by dictionary lookup position.

**Comment by izziiyt** [comment]
I can't find clues with just simple investigation.  
Please write SudachiPy version and dictionary version you used. Thanks.

**Comment by KHiyowa** [comment]
Sudachi(Java): 0.3.0
SudachiPy: 0.3.11
Dict: SudachiDict_core-20190718

thanks.
