### ISSUE TITLE
parsing user-dictionary name

### ISSUE THREAD

**Issue by KHiyowa** [WorksApplications/SudachiPy#83]
I wrote
"userDict" : "year.dic"
in sudachi.json and execute command line sudachipy, caused an error

FileNotFoundError: [Errno 2] No such file or directory: '~~/sudachipy/resources/y'

I rename 'year.dic' to 'y' ,wrote "userDict" : "y" in sudachi.json and execute, it can run normaly.

**Comment by yummydum** [comment]
Although the document states that sudachi.json should be configured like below, 

```
{
    "userDict" : "relative/path/to/user.dic",
    ...
}
```
the code iterates over this dict["userDict"] as below (iteration on string). 
https://github.com/WorksApplications/SudachiPy/blob/07d31beed246ddbb496b29f06a5167c373e1db0e/sudachipy/config.py#L119

Thus only the first character appears in the error message. 
I replaced the values as a list, and then it works fine. 
```
{
    "userDict" : ["relative/path/to/user.dic"],
    ...
}
```

**Comment by izziiyt** [comment]
@KHiyowa @yummydum Thanks. I'll update README.md
