### ISSUE TITLE
What's the tagset used by SudachiPy?

### ISSUE THREAD

**Issue by BLKSerene** [WorksApplications/SudachiPy#88]
Hi, thanks for the great SudachiPy and I'm using it in my own project. I'm wondering that is there any reference for the tagset used by SudachiPy, since I want to convert the POS tags to [universal POS tags](http://universaldependencies.org/u/pos/all.html)?

**Comment by izziiyt** [comment]
@BLKSerene Thank you for using and FB !

@kazuma-t Is there postag list, used in Sudachi, on public URL ?

**Comment by fhudi** [comment]
Hi @BLKSerene, Sudachi is **based on [UniDic](https://unidic.ninjal.ac.jp/)**

You can use following public URL as a reference: https://hayashibe.jp/tr/mecab/dictionary/unidic/pos

**Comment by BLKSerene** [comment]
@lintaoren Thanks for the information!
